apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: jenkins
  labels:
    app: demo
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: blue
  template:
    metadata:
      labels:
        app: demo
        version: blue
    spec:
      containers:
      - name: app
        image: crpi-v1qihtqp9ipem36a.cn-shanghai.personal.cr.aliyuncs.com/imbucket/bucket:blue
        ports:
        - containerPort: 8090
        env:
        - name: APP_VERSION
          value: "blue"
