apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: demo
    version: blue # Change this to 'green' to switch environments
